apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: k8s.lab.local
    http:
      paths:
      - path: /cat
        backend:
          serviceName: nginx-service-cat
          servicePort: 80
      - path: /dog
        backend:
          serviceName: nginx-service-dog
          servicePort: 80
      - path: /rabbit
        backend:
          serviceName: nginx-service-rabbit
          servicePort: 80
